name: GnanG
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: "0.4.3"
  http: "0.11.3+17"
  flame: "0.10.0"
  onesignal: "1.0.5"
  firebase_core:
  firebase_messaging: "0.2.1"
  flutter_spinkit: "3.1.0"
  flare_flutter: "1.0.7"

  # For Puzzle -
  # cupertino_icons: ^0.1.2
  fluttertoast: "2.2.2"
  url_launcher: "4.0.3"
  share: "0.5.3"
  color: any
  rxdart: "0.20.0"
  encrypt: "1.0.0+1"
  connectivity: "0.3.2"
  nima: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: "0.1.2"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/TZLogo.jpg
    - images/coin.png
    - images/face.png
    - images/planet.png
    - images/logo.png
    - images/bkg.jpg
    - images/login.jpg
    - images/logo1.png
    - images/face.jpg
    - images/rank2.jpg
    - images/rank3.jpg
    - assets/audio/music/CV-01Trimantra.mp3
    - assets/audio/music/Pac man dies.mp3
    - assets/audio/music/party_horn-Mike_Koenig-76599891.mp3
    - assets/audio/music/bensound-epic.mp3
    - assets/animation/noInternet.flr
    - assets/animation/Teddy.flr
    - assets/animation/Dancing.flr
    - assets/animation/leaderboard.flr
    - assets/animation/person_floating.flr
    - assets/animation/bonus.flr
    - assets/animation/leader.flr
    - assets/animation/puzzl.flr
    
    


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CmSans
      fonts:
        - asset: fonts/CmSans.ttf
          weight: 500
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
